import { createSlice } from "@reduxjs/toolkit";

const initialCars = [
  {
    id: 1,
    brand: "Chevrolet",
    model: "Onix",
    year: 2024,
    color: "White",
    price: 17800,
    mileage: 12000,
    fuel: "Petrol",
    transmission: "Automatic",
    favorite: false,
    status: "Available",
    image: "/images/onix.jpg",
  },
  {
    id: 2,
    brand: "Chevrolet",
    model: "Cobalt",
    year: 2023,
    color: "Black",
    price: 14500,
    mileage: 35000,
    fuel: "Propan",
    transmission: "Manual",
    favorite: false,
    status: "Available",
    image: "/images/cobalt.jpg",
  },
  {
    id: 3,
    brand: "Kia",
    model: "K5",
    year: 2025,
    color: "Gray",
    price: 32500,
    mileage: 5000,
    fuel: "Petrol",
    transmission: "Automatic",
    favorite: false,
    status: "Sold",
    image: "/images/k5.jpg",
  },
  {
    id: 4,
    brand: "Hyundai",
    model: "Elantra",
    year: 2022,
    color: "Blue",
    price: 21000,
    mileage: 42000,
    fuel: "Petrol",
    transmission: "Automatic",
    favorite: false,
    status: "Available",
    image: "/images/elantra.jpg",
  },
  {
    id: 5,
    brand: "Toyota",
    model: "Camry",
    year: 2024,
    color: "Silver",
    price: 34000,
    mileage: 8000,
    fuel: "Hybrid",
    transmission: "Automatic",
    favorite: false,
    status: "Reserved",
    image: "/images/camry.avif",
  },
  {
    id: 6,
    brand: "BMW",
    model: "X5",
    year: 2021,
    color: "Black",
    price: 55000,
    mileage: 65000,
    fuel: "Diesel",
    transmission: "Automatic",
    favorite: false,
    status: "Available",
    image: "/images/x5.jpg",
  },
  {
    id: 7,
    brand: "Mercedes",
    model: "C200",
    year: 2023,
    color: "White",
    price: 47000,
    mileage: 18000,
    fuel: "Petrol",
    transmission: "Automatic",
    favorite: false,
    status: "Sold",
    image: "/images/c200.jpg",
  },
  {
    id: 8,
    brand: "Tesla",
    model: "Model 3",
    year: 2025,
    color: "Red",
    price: 41000,
    mileage: 3000,
    fuel: "Electric",
    transmission: "Automatic",
    favorite: false,
    status: "Available",
    image: "/images/model3.jpg",
  },
];

const carSlice = createSlice({
  name: "cars",
  initialState: {
    items: initialCars,
  },
  reducers: {
    deleteCar: (state, action) => {
      state.items = state.items.filter((car) => car.id !== action.payload);
    },
  },
});

export const { deleteCar } = carSlice.actions;
export default carSlice.reducer;
